spring.application.name=ShortQR-URL Shortner and QR Generator

spring.datasource.url=jdbc:postgresql://localhost:5432/ShortQR
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

app.base-url=${APP_BASE_URL:http://localhost:8080}