spring.application.name=ShortQR-URL Shortner and QR Generator

spring.datasource.url=jdbc:postgresql://localhost:5432/ShortQR
spring.datasource.username=postgres
spring.datasource.password=707170

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false